import type { Metadata } from "next";
import Link from "next/link";
import { Breadcrumbs } from "@/components/ui/Breadcrumbs";
import { breadcrumbListSchema, jsonLdScriptProps } from "@/lib/jsonld";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://aicompliancehub.com";

export const metadata: Metadata = {
  title: "Pro Compliance Report — Detailed AI Regulation Gap Analysis ($49)",
  description:
    "Get a detailed AI compliance gap analysis report with NIST AI RMF mapping, specific action items, and timeline recommendations. Generated by AI compliance experts.",
  alternates: {
    canonical: `${SITE_URL}/checker/pro-report`,
  },
};

const WHATS_INCLUDED = [
  {
    icon: "📋",
    title: "Full Regulatory Mapping",
    description:
      "Every regulation that applies to your business, with specific obligations broken out by category. No vague summaries — exact requirements.",
  },
  {
    icon: "🎯",
    title: "Gap Analysis",
    description:
      "Your current compliance posture vs. what's required. We identify exactly what you're missing and prioritize by legal risk.",
  },
  {
    icon: "🗺",
    title: "NIST AI RMF Alignment",
    description:
      "Your obligations mapped to the NIST AI Risk Management Framework so you can build one governance program that covers all your regulations.",
  },
  {
    icon: "✅",
    title: "Action Plan with Timelines",
    description:
      "A prioritized, deadline-driven action plan. Which items are due before which enforcement dates. What to do first.",
  },
  {
    icon: "📄",
    title: "Downloadable PDF Report",
    description:
      "A professional report you can share with your legal team, board, or external auditors as evidence of compliance due diligence.",
  },
  {
    icon: "🔄",
    title: "30-Day Update Guarantee",
    description:
      "If a relevant regulation changes within 30 days of your report, we send you an updated version at no additional charge.",
  },
];

const SAMPLE_REGULATIONS = [
  { name: "EU AI Act", status: "High-risk obligations apply", urgency: "high" },
  { name: "NYC Local Law 144", status: "Annual bias audit required", urgency: "high" },
  { name: "Colorado AI Act", status: "Impact assessment required by June 2026", urgency: "medium" },
  { name: "California AB 2013", status: "Training data transparency report required", urgency: "medium" },
  { name: "Illinois AIVIRA", status: "Candidate consent required", urgency: "low" },
];

export default function ProReportPage() {
  const breadcrumbs = breadcrumbListSchema([
    { name: "Home", url: "/" },
    { name: "Compliance Checker", url: "/checker" },
    { name: "Pro Report", url: "/checker/pro-report" },
  ]);

  return (
    <>
      <script {...jsonLdScriptProps(breadcrumbs)} />

      {/* Header */}
      <div className="border-b border-neutral-200 bg-white">
        <div className="mx-auto max-w-4xl px-4 py-10 sm:px-6 lg:px-8">
          <Breadcrumbs
            items={[
              { label: "Home", href: "/" },
              { label: "Compliance Checker", href: "/checker" },
              { label: "Pro Report" },
            ]}
          />
          <div className="mt-4 flex flex-col sm:flex-row sm:items-start sm:justify-between gap-6">
            <div>
              <div className="inline-flex items-center gap-2 rounded-full bg-amber-100 px-3 py-1 text-xs font-medium text-amber-700 mb-3">
                <svg className="h-3.5 w-3.5" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true">
                  <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                </svg>
                Pro Report
              </div>
              <h1 className="text-3xl font-extrabold tracking-tight text-neutral-900">
                Detailed AI Compliance Gap Analysis
              </h1>
              <p className="mt-2 text-neutral-600 leading-relaxed max-w-xl">
                Go beyond the free checker. Get a detailed report that maps your specific situation to every applicable regulation — with a prioritized action plan and PDF you can share with your team.
              </p>
            </div>
            <div className="shrink-0 rounded-2xl border border-neutral-200 bg-neutral-50 p-5 text-center sm:min-w-[180px]">
              <div className="text-4xl font-extrabold text-neutral-900">$49</div>
              <div className="text-sm text-neutral-500 mt-0.5">one-time payment</div>
              <div className="text-xs text-neutral-500 mt-1">PDF + 30-day updates</div>
            </div>
          </div>
        </div>
      </div>

      <div className="mx-auto max-w-4xl px-4 py-10 sm:px-6 lg:px-8 space-y-12">

        {/* Sample report preview */}
        <section>
          <h2 className="text-lg font-bold text-neutral-900 mb-4">Sample: What Your Report Includes</h2>
          <div className="rounded-xl border border-neutral-200 bg-white overflow-hidden">
            <div className="px-5 py-3 bg-neutral-50 border-b border-neutral-200 flex items-center gap-2">
              <div className="h-3 w-3 rounded-full bg-red-400" />
              <div className="h-3 w-3 rounded-full bg-amber-400" />
              <div className="h-3 w-3 rounded-full bg-green-400" />
              <span className="ml-2 text-xs font-mono text-neutral-500">AI Compliance Gap Analysis Report.pdf</span>
            </div>
            <div className="p-5">
              <div className="mb-4">
                <h3 className="font-bold text-neutral-900 mb-1">Regulations Applicable to Your Business</h3>
                <p className="text-xs text-neutral-500 mb-3">Based on: SaaS company · US + EU operations · Hiring AI + LLM product</p>
                <div className="space-y-2">
                  {SAMPLE_REGULATIONS.map((reg) => (
                    <div key={reg.name} className="flex items-center justify-between gap-3 text-sm">
                      <span className="font-medium text-neutral-800">{reg.name}</span>
                      <span className={`text-xs font-medium px-2 py-0.5 rounded-full ${
                        reg.urgency === "high" ? "bg-red-100 text-red-700" :
                        reg.urgency === "medium" ? "bg-amber-100 text-amber-700" :
                        "bg-neutral-100 text-neutral-600"
                      }`}>
                        {reg.status}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
              <div className="border-t border-neutral-100 pt-4">
                <h3 className="font-bold text-neutral-900 mb-2">Priority Action Items</h3>
                <ol className="space-y-1.5 text-sm text-neutral-600">
                  <li className="flex gap-2"><span className="text-red-500 font-bold">1.</span> Commission NYC LL 144 bias audit before Q3 2026</li>
                  <li className="flex gap-2"><span className="text-red-500 font-bold">2.</span> Complete EU AI Act high-risk system documentation by July 2026</li>
                  <li className="flex gap-2"><span className="text-amber-600 font-bold">3.</span> Complete Colorado AI Act impact assessment by May 2026</li>
                  <li className="flex gap-2"><span className="text-amber-600 font-bold">4.</span> Publish California AB 2013 training data transparency report by December 2026</li>
                  <li className="flex gap-2"><span className="text-neutral-500 font-bold">5.</span> Add Illinois AIVIRA candidate notices to hiring process</li>
                </ol>
              </div>
              <div className="mt-4 text-xs text-neutral-500 italic">
                Plus: NIST AI RMF mapping, full obligation checklists per regulation, vendor compliance requirements, and implementation templates.
              </div>
            </div>
          </div>
        </section>

        {/* What's included */}
        <section>
          <h2 className="text-lg font-bold text-neutral-900 mb-5">What&apos;s Included</h2>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            {WHATS_INCLUDED.map((item) => (
              <div key={item.title} className="flex items-start gap-3 rounded-xl border border-neutral-200 bg-white p-4">
                <span className="text-xl shrink-0" role="img" aria-label={item.title}>{item.icon}</span>
                <div>
                  <h3 className="font-semibold text-neutral-900 text-sm">{item.title}</h3>
                  <p className="mt-0.5 text-sm text-neutral-600 leading-relaxed">{item.description}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* CTA */}
        <section className="rounded-2xl bg-brand-900 px-6 py-8 sm:px-10 text-center">
          <h2 className="text-xl font-bold text-white">
            Get Your Pro Compliance Report
          </h2>
          <p className="mt-2 text-brand-200 text-sm max-w-md mx-auto">
            First, complete the free compliance checker to tell us about your business. Then upgrade for the full report.
          </p>
          <div className="mt-6 flex flex-col sm:flex-row gap-3 justify-center">
            <Link
              href="/checker"
              className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-6 py-3 text-sm font-bold text-brand-900 hover:bg-brand-50 transition-colors shadow-sm"
            >
              Start Free Checker First
              <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2} aria-hidden="true">
                <path strokeLinecap="round" strokeLinejoin="round" d="M17 8l4 4m0 0l-4 4m4-4H3" />
              </svg>
            </Link>
          </div>
          <p className="mt-4 text-xs text-brand-400">
            Payment processing coming soon — join the waitlist via the free checker.
          </p>
        </section>

        {/* Free vs Pro comparison */}
        <section>
          <h2 className="text-lg font-bold text-neutral-900 mb-5">Free vs. Pro</h2>
          <div className="overflow-x-auto rounded-xl border border-neutral-200">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-neutral-200 bg-neutral-50">
                  <th className="px-5 py-3 text-left font-semibold text-neutral-700">Feature</th>
                  <th className="px-5 py-3 text-center font-semibold text-neutral-700">Free</th>
                  <th className="px-5 py-3 text-center font-semibold text-brand-700">Pro ($49)</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-neutral-100">
                {[
                  ["Identifies applicable regulations", true, true],
                  ["Required action overview", true, true],
                  ["Links to regulation guides", true, true],
                  ["Detailed obligation breakdown by law", false, true],
                  ["NIST AI RMF mapping", false, true],
                  ["Gap analysis vs. current posture", false, true],
                  ["Prioritized action plan with deadlines", false, true],
                  ["Downloadable PDF report", false, true],
                  ["30-day update guarantee", false, true],
                  ["Board-ready summary", false, true],
                ].map(([feature, free, pro]) => (
                  <tr key={String(feature)} className="bg-white">
                    <td className="px-5 py-3 text-neutral-700">{feature}</td>
                    <td className="px-5 py-3 text-center">
                      {free ? (
                        <span className="text-green-600">✓</span>
                      ) : (
                        <span className="text-neutral-300">—</span>
                      )}
                    </td>
                    <td className="px-5 py-3 text-center">
                      {pro ? (
                        <span className="text-brand-700 font-bold">✓</span>
                      ) : (
                        <span className="text-neutral-300">—</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        <p className="text-xs text-neutral-500 leading-relaxed text-center">
          Not legal advice. This report is for informational purposes only. Always consult a qualified attorney for compliance decisions.
        </p>
      </div>
    </>
  );
}
